[tools]
# Core
go = "1.25.1"
java = "openjdk-24.0.0"
node = "24.7.0"
python = "3.13.7"
rust = { version = "1.89.0", components = "rustc,cargo,rustfmt,rust-docs,rust-analyzer,clippy" }
# Plugins
kotlin = "2.2.0"
cosign = "2.5.3"
bat = "0.25.0"
btop = "1.4.0"
cmake = "4.1"
"cargo:eza" = "0.23.0"
jq = "1.8.1"
#make = "4.4"
neovim = "0.11.4"
"pipx:nox[uv]" = "2025.5.1"
opentofu = "1.10.6"
uv = "0.8.16"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"

[settings.python]
compile = true
uv_venv_auto = true
