[tools]
# Core
go = "1.25.1"
java = "openjdk-21.0"
node = "24.7.0"
python = "3.12.1"
rust = { version = "1.82.0", components = "rustc,cargo,rustfmt,rust-docs,rust-analyzer,clippy" }
# Plugins
kotlin = "2.2.0"
uv = "0.8.15"
"cargo:eza" = "0.23.0"
"pipx:nox[uv]" = "2025.2.9"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"

[settings.python]
compile = true
uv_venv_auto = true
