[tools]
# Core
java = "latest"
node = "lts"
python = "latest"
rust = { version = "latest", components = "rustc,cargo,rustfmt,rust-docs,rust-analyzer,clippy" }
# Plugins
kotlin = "latest"
uv = "latest"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"

[settings.python]
compile = true
uv_venv_auto = true
