name: Build Container

on:
  schedule:
    - cron: "25 14 1 * *"
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/build-container.yml@9c2b284f6fb48a4b294728b63fa4032b15104e00
    secrets: inherit
