name: Build Container

on:
  schedule:
    - cron: "25 14 1 * *"
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/build-container.yml@b3eca7b29c022f0d6c7446b24e9270d8c2f5b45c
    secrets: inherit
