name: Build Container

on:
  schedule:
    - cron: "25 14 1 * *"
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/build-container.yml@e559e09f21dfd8f3bc6c465c736712cbb9e976ab
    secrets: inherit
