name: Lint Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  actionlint:
    uses: FasterSpeeding/Piped/.github/workflows/lint-actions.yml@a1c6aca923b5573149ceaf81f0a00e2d598ad9ec
    secrets: inherit
