name: Lint Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  actionlint:
    uses: FasterSpeeding/Piped/.github/workflows/lint-actions.yml@649f1011197e91bd6126c9c58ae44a4676221edf
    secrets: inherit
