name: Lint Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  actionlint:
    uses: FasterSpeeding/Piped/.github/workflows/lint-actions.yml@b3eca7b29c022f0d6c7446b24e9270d8c2f5b45c
    secrets: inherit
