name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@a1c6aca923b5573149ceaf81f0a00e2d598ad9ec
    secrets: inherit
