name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@e9f2ab192ad422bf8ba19817ef977b594d4fa444
    secrets: inherit
