name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@649f1011197e91bd6126c9c58ae44a4676221edf
    secrets: inherit
