# FILE SYNCED from https://github.com/FasterSpeeding/devcontainer

[tools]
# Languages
go = "1.25.1"
java = "openjdk-24.0.0"
node = "24.8.0"
python = "3.13.7"
rust = { version = "1.90.0", components = "rustc,cargo,rustfmt,rust-docs,rust-analyzer,clippy" }
kotlin = "2.2.20"
# CLI and Dev tools
bat = "0.25.0"
btop = "1.4.0"
cmake = "4.1"
cosign = "2.5.3"
"cargo:eza" = "0.23.0"
git-lfs = "3.7.0"
jq = "1.8.1"
just = "1.42.4"
make = "4.4.1"
neovim = "0.11.4"
ninja = "1.13.1"
"pipx:nox[uv]" = "2025.5.1"
opentofu = "1.10.6"
yq = "4.47.2"
uv = "0.8.19"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"

[settings.python]
compile = true
uv_venv_auto = true
