# File synced from https://github.com/FasterSpeeding/devcontainer
# Changes will not be persisted
[tools]
# Languages
go = "1.26.5"
java = "openjdk-25.0.0"
lua = "5.5"
node = "24.20.0"
python = "3.14.7"
rust = { version = "1.98.0", components = "rustc,cargo,rustfmt,rust-docs,rust-analyzer,clippy" }
kotlin = "2.4.10"
# CLI and Dev tools
bat = "0.26.1"
btop = "1.4.7"
bun = "1.3.14"
cargo-binstall = "1.22.0"
chezmoi = "2.71.0"
claude = "2.1.251"
cmake = "4.4.3"
cosign = "3.1.1"
"cargo:eza" = "0.23.0"
flux2 = "2.9.2"
git-lfs = "3.8.0"
helm = "4.2.4"
jq = "1.8.2"
just = "1.58.0"
"pipx:kseal" = "2.1.1"
kubectl = "1.37.0"
kubeseal = "0.39.1"
k9s = "0.59.0"
make = "4.4.1"
neovim = "0.12.5"
ninja = "1.13.2"
"pipx:nox[uv]" = "2026.8.17"
opentofu = "1.12.4"
tmux = "3.7c"
yq = "4.53.6"
uv = "0.12.7"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"

[settings.python]
compile = true
